import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.special import lambertw
import matplotlib.animation as animation

# Configuration for academic style visualization
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 12,
    "axes.labelsize": 14,
    "axes.titlesize": 16
})

# 1. Calculate n* (as done in the main proof code)
arg = -1/(2*np.e)
W_val = lambertw(arg, k=-1)
n_star = -W_val.real
D = 3

# 2. Define the Information Functional (Potential Energy Landscape)
def InformationFunctional(n):
    # Calculate the functional value
    F_n = n*np.log(2*n) - 0.5*n**2
    # Shift the functional so the minimum (at n*) is at 0 for visualization
    F_min = n_star*np.log(2*n_star) - 0.5*n_star**2
    return F_n - F_min

# 3. Define the Figure-8 Knot Parametrization
def figure_eight_knot(t):
    # Standard parametrization for 4_1 knot
    x = (2 + np.cos(2*t)) * np.cos(3*t)
    y = (2 + np.cos(2*t)) * np.sin(3*t)
    z = np.sin(4*t)
    return x, y, z

# 4. Setup the Visualization Figure
fig = plt.figure(figsize=(15, 7))
plt.suptitle("Axiomatic Framework Visualization: Gradient Descent and Topology", fontsize=18)

# === Plot 1: Information Functional and Gradient Descent ===
ax1 = fig.add_subplot(121)
n_values = np.linspace(2.0, 3.5, 500)
F_values = InformationFunctional(n_values)

ax1.plot(n_values, F_values, 'k-', linewidth=2, label='Information Functional $\mathcal{F}(n)$')
ax1.axvline(n_star, color='r', linestyle='--', label=f'$n^*$ ≈ {n_star:.4f} (Minimum)')
ax1.axvline(D, color='b', linestyle=':', label='$D=3$ (Topological Requirement)')

# The floating "Tension 5" text from your image is not generated by this code.
# The original code had a "Tension delta" label. I have commented it out.
# To restore it, uncomment the following two lines:
# ax1.annotate('', xy=(n_star, -0.01), xytext=(D, -0.01),
#              arrowprops=dict(arrowstyle='<->', color='purple', lw=1.5))
# ax1.text((n_star + D)/2, -0.02, 'Tension', color='purple', ha='center', va='top')


ax1.set_xlabel("Effective Dimensionality (n)")
ax1.set_ylabel("$\mathcal{F}(n)$ (Potential)")
ax1.set_title("Gradient Descent Toward Stability $n^*$")
ax1.legend(loc='best') # Changed to 'best' to avoid overlap
ax1.grid(True, linestyle=':', alpha=0.6)
# Adding a point at the minimum for clarity
ax1.plot(n_star, 0, 'ro') 

# === Plot 2: Figure-8 Knot Topology (Information Flow Manifold) ===
ax2 = fig.add_subplot(122, projection='3d')
t = np.linspace(0, 2*np.pi, 500)
x, y, z = figure_eight_knot(t)

# Color map based on the parameter t to visualize the flow
colors = plt.cm.viridis(t / (2*np.pi))
for i in range(len(t)-1):
    ax2.plot(x[i:i+2], y[i:i+2], z[i:i+2], color=colors[i], linewidth=4)

ax2.set_title("Figure-8 Knot ($4_1$): Information Flow Manifold")
ax2.set_xlabel("X")
ax2.set_ylabel("Y")
ax2.set_zlabel("Z")
ax2.grid(False) # Remove gridlines for a cleaner look

# === Animation: Gradient Descent and Knot Rotation ===

# Initial state for gradient descent animation (starting at n=3.3)
n_start = 3.3
gd_point, = ax1.plot(n_start, InformationFunctional(n_start), 'go', markersize=10, label="System State")

def update(frame):
    # Update Gradient Descent
    total_frames = 150
    n_end = n_star
    
    if frame < total_frames:
        n_current = n_end + (n_start - n_end) * np.exp(-5 * frame/total_frames)
        gd_point.set_data(n_current, InformationFunctional(n_current))
    else:
        gd_point.set_data(n_star, InformationFunctional(n_star))

    # Update Knot Rotation
    ax2.view_init(elev=20., azim=frame * 0.5)
    return gd_point,

# Create the animation
print("\nGenerating Academic Visualization (Animation)...")
ani = animation.FuncAnimation(fig, update, frames=400, interval=30, blit=False, repeat=True)

# *** THE FIX IS HERE ***
# Replaced plt.tight_layout(rect=[...]) with a simple call.
plt.tight_layout()

plt.show()